language: php
cache:
  bundler: true
  apt: true
  directories:
  - vendor
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
install:
- sudo apt-get update > /dev/null
- composer selfupdate
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:6.*
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone --branch 8.x-1.x http://git.drupal.org/project/composer.git ~/.drush/composer
- drush dl drupal --default-major=7 -y
- mv drupal-* drupal
- mv composer.json drupal/profiles/standard/.
- mkdir -p drupal/sites/all/modules/contrib/lightning_features
- mv lightning_* drupal/sites/all/modules/contrib/lightning_features/.
- ls -l
- cd drupal
- drush make --no-core sites/all/modules/contrib/lightning_features/lightning_features.make -y
- drush si standard --db-url=mysql://root:@localhost/drupal -y
before_script:
- drush en lightning_* -y
- drush dis dblog -y
- drush cc all
- drush runserver --server=builtin 8080 &
- sleep 4
script:
- drush uli -l http://127.0.0.1:8080 -v
notifications:
  slack:
    secure: qYAAGggrJev5pQe6+9ZlMcXmeP9XI/xH9x6k84fGKpYa8PQ6NLfBAcz1+ibBkXtDycaKKGQ4ny3YCOQJcCkGkISrLsN+3nFJN8f/TxGRVER456wweCQsDyIoXiNkI4e5mjmZMsz/dyw2DYF9fcBe7z8ka5N33IP7cyIWcRcAkRgOxqfkuFIaeU9RSMbua9n/E50IW7M3w3d4mpWt4zWOR2uwumqlYFTnrUNUna9iYCsfD9axqrY89PH11/NLRO/qNITAMabikyqbW/Wmu6GLb8iHt8TpX+daLHa98R0ibluRhZ+cSWRGRz6UDLjzcZP9OU9B8OvWs6ZnN5JFc2zthNiEUsfrOz9HVXrKuY60Uc8YOt3wa2yR1kJIu8EgBca62mUTunn6L6dGjCY2BfriVntgutwlfWvdzF0bd5JafYBEMexSqGsQr3YJhAIQfbauzltzX1rkDkoVb87sWC+Yx8WKojq8zkdSrsa2YuWJ4UNGpqbtc9HAei48juVvnqssuyt4CA/q7+B1dTgfflAcA0CeGJ6Lxmvdc+T72BrRzQZIpXuqfSQFrXdKDlh/H7PYRTnX8L7e9xaQnJ7XDxoncutmdkB1nsUST+38/xfG4PG3phgOH19fIuTk1jtA9iVTDaDEXpUWdwvks4lKsOPfh0LdcuJBodKvdqaJMIyPXrs=
matrix:
  fast_finish: true
